
name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
          pip install ray[default]
    - name: check cpu
      run: |
          python -c "import ray; ray.init(), print (ray.available_resources())"
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
          docker build -t sd:latest .
          docker run sd:latest sh -c 'pip freeze'
          
