
name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: make build
    - name: test
      run: make test
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        #with:
        #  python-version: 3.10
      - run: pip install . 
      - run: mkdocs gh-deploy --force