
name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
          pip install ray[default]
    - name: check cpu
      run: |
          python -c "import ray; ray.init(), print (ray.available_resources())"
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
          python -m venv venv
          . ./venv/bin/activate
          python -m pip install --upgrade pip
          pip install -u .
          pip install -u mkdocs mkdocs-material mkdocstrings[python]
          mkdocs gh-deploy --force
          
